### PR TITLE
Run yapf on Python files

### LINKED ISSUE #22: Follow a single code style
Would anyone oppose following a single style? We don't have to enforce it, but would be nice to have `autopep8` or `flake8` issues fixed for easier code reading.

### PR DESCRIPTION
**Pull request by aprokop**
This is simply an example of how we could come to a style. I used [yapf](https://github.com/google/yapf) tool, that was run on all Python files. I care less about the details of a style, and more about having one. 

If we don't like how some of the code was formatted, it can be disabled for those pieces of code using `# yapf: disable`.

If we agree that this (or a modification of it) is a style we want to have, we would want to install the pre-commit hooks in our local repos to make sure all commits follow it.

Thoughts?

Fix #22. I also had to fix `Dataloader.py` as it was carrying the wrong new lines code (probably created in Windows).

### CODE REVIEW

**Comment by allaffa** [comment]
I think that the style format is pretty good. Also, as you mention, I like the fact that we can locally disable the style formatting using `# yapf: disable` when it is specifically needed.

**Comment by aprokop** [comment]
So, right now the style is not being enforced or checked. I would encourage people to set up github hooks to auto-check that locally.

That's easy to do: just copy [this](https://github.com/google/yapf/blob/master/plugins/pre-commit.sh) file to your `.git/hooks`, change its permssion, and that's it. Now, next time you try to `git commit`, that fill fail if you haven't run yapf on the code.

**Comment by VittorioGabbi** [comment]
Sounds like a good idea to me, I've downloaded it and tried it already,
I'll use it from now onward

**Comment by vitst** [comment]
@aprokop, quick question, I used `yapf` on the current files and it formats them differently. Do we have particular file format settings?

**Comment by aprokop** [comment]
@vitst You bring out a good point, we never specified the version (or settings). I used yapf 0.20.1 (coming with Ubuntu 18.04) with default settings, which should have formatted it to `pep8` and not `google`. We could add `.style.yapf` in the root for consistency, or simply use the same version.

**Comment by vitst** [comment]
I think to have a style file added to the repository is a better idea. @aprokop could you please add your version file then?

**Pull request merged**
